name = "SafeVerify"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["safe_verify","SafeVerify"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.9.0"

[[lean_lib]]
name = "SafeVerify"

[[lean_exe]]
name = "safe_verify"
root = "Main"
supportInterpreter = true

